from tkinter import *
import tkinter.font
import random
SCREEN = Tk()
SCREEN.geometry("500x300")
SCREEN.config(background=("Green"))
rps = Label(SCREEN,text="Rock Paper Scissors")
rps.place(x=200,y=10)
winning = Label(SCREEN,text="Let's Start the game.")
winning.place(x=200,y=50)
optionsl = Label(SCREEN,text="Your options")
optionsl.place(x=200,y=80)
rock = Button(SCREEN,text="rock",font=("Comic Sans MS",30))
paper  = Button(SCREEN,text="paper",font=("Comic Sans MS",30))
scissors = Button(SCREEN,text="scissors",font=("Comic Sans MS",30))
rock.place(x=10,y=120)
paper.place(x=150,y=120)
scissors.place(x=320,y=120)
scorelabel = Label(SCREEN,text="Score = ",font=("Comic Sans MS",18))
scorelabel.place(x= 10,y=230)
mescorelab = Label(SCREEN,text="Your score: ")
mescorelab.place(x=120,y=220)
npcscorelab = Label(SCREEN,text="Computer score: ")
npcscorelab.place(x=120,y=260)
meselectlab = Label(SCREEN,text="You Selected: ")
meselectlab.place(x=300,y=220)
npcselectlab = Label(SCREEN,text="Computer Selected: ")
npcselectlab.place(x=300,y=260)
mainloop()